services:
  web:
    build: .
    container_name: revoubank-app
    command: gunicorn -w 4 -b 0.0.0.0:5000 app.main:app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7
    container_name: revoubank-redis
    ports:
      - "6379:6379"
    restart: always
