version: '3.8'

services:
  web:
    build: .
    container_name: revoubank-web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: revoubank-db
    restart: always
    environment:
      POSTGRES_USER: revou
      POSTGRES_PASSWORD: revou123
      POSTGRES_DB: revoubank
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
