"""Add role column to users

Revision ID: 086f3ce157d8
Revises: f31b1137cfa5
Create Date: 2025-04-02 22:49:19.583935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086f3ce157d8'
down_revision = 'f31b1137cfa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
