"""Add account_number to accounts

Revision ID: f31b1137cfa5
Revises: 11ea947d17d3
Create Date: 2025-03-27 06:28:08.610908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31b1137cfa5'
down_revision = '11ea947d17d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('account_number',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('account_number',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
